# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virouser',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Ид'),
        ),
    ]
