# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0002_auto_20170620_2204'),
        ('customuser', '0002_auto_20170620_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virouser',
            options={'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='virouser',
            name='criterion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion', verbose_name='Критерии'),
        ),
    ]
