# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0005_auto_20170620_2231'),
        ('customuser', '0003_auto_20170620_2204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virouser',
            name='criterion',
        ),
        migrations.AddField(
            model_name='virouser',
            name='criterion',
            field=models.ManyToManyField(default=1, to='criterion.Criterion', verbose_name='Критерии'),
        ),
    ]
