# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_auto_20170624_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
    ]
