# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_auto_20170625_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='virouser',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Ид'),
            preserve_default=False,
        ),
    ]
