# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0007_virouser_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virouser',
            name='number',
            field=models.IntegerField(verbose_name='Ид'),
        ),
    ]
