# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criterion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(default='2017', max_length=4, verbose_name='Год проведения')),
                ('number', models.CharField(default=1, max_length=5, verbose_name='Номер')),
                ('ages', models.CharField(blank=True, max_length=40, verbose_name='Возраст детей')),
                ('description', models.CharField(max_length=300, verbose_name='Описание')),
                ('deadline', models.CharField(blank=True, max_length=100, verbose_name='Срок проведения')),
                ('goal', models.CharField(blank=True, max_length=300, verbose_name='Цель')),
                ('responsible', models.CharField(blank=True, max_length=100, verbose_name='Ответственный за проведение')),
                ('subject', models.CharField(blank=True, max_length=300, verbose_name='Предмет исследования')),
                ('tools', models.CharField(blank=True, max_length=300, verbose_name='Диагностический инструментарий')),
            ],
            options={
                'verbose_name': 'Критерий',
                'verbose_name_plural': 'Критерии',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='CriterionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Район пользователя')),
                ('criterion', models.ManyToManyField(to='criterion.Criterion')),
            ],
            options={
                'verbose_name': 'Список критериев',
            },
        ),
    ]
