# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='Номер'),
        ),
    ]
