# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterionlist',
            options={'verbose_name': 'Список критериев', 'verbose_name_plural': 'Список критериев'},
        ),
    ]
