# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
        migrations.AddField(
            model_name='criterion',
            name='ages',
            field=models.CharField(blank=True, max_length=40, verbose_name='Возраст детей'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='conclusion',
            field=models.TextField(blank=True, verbose_name='Выводы'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='deadline',
            field=models.CharField(blank=True, max_length=300, verbose_name='Срок проведения'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='goal',
            field=models.CharField(blank=True, max_length=300, verbose_name='Цель'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='qnt',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во детей данного возраста в МОУ'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='qntExam',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Из них обследовано'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='responsible',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ответственный за проведение'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='subject',
            field=models.CharField(blank=True, max_length=300, verbose_name='Предмет исследования'),
        ),
        migrations.AddField(
            model_name='criterion',
            name='tools',
            field=models.CharField(blank=True, max_length=300, verbose_name='Диагностический инструментарий'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='number',
            field=models.CharField(default=1, max_length=5, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='criterion',
            name='year',
            field=models.CharField(default='2016', max_length=4, verbose_name='Год проведения'),
        ),
    ]
