# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0002_auto_20170628_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='year',
            field=models.PositiveSmallIntegerField(default=2017, verbose_name='Год проведения'),
        ),
    ]
