# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0004_auto_20170620_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criterion',
            options={'ordering': ('number',), 'verbose_name': 'Критерий', 'verbose_name_plural': 'Критерии'},
        ),
    ]
