# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0005_auto_20170620_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion')),
            ],
        ),
    ]
