# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-25 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0006_criterionlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterionlist',
            name='criterion',
        ),
        migrations.AddField(
            model_name='criterionlist',
            name='criterion',
            field=models.ManyToManyField(to='criterion.Criterion'),
        ),
    ]
