# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('value', models.CharField(default=0, max_length=500, verbose_name='Значение')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion', verbose_name='Критерий')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
