# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-22 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('criterion', '0005_auto_20170620_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Название')),
                ('value', models.CharField(max_length=500, verbose_name='Значение')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
