# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер'),
        ),
    ]
