# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(default=0, max_length=500, verbose_name='Значение'),
        ),
    ]
