# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-08 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('criterion', '0002_auto_20170708_2334'),
        ('answer', '0002_auto_20170708_1926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together=set([('number', 'criterion')]),
        ),
    ]
