# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20170627_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='criterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterion.Criterion', verbose_name='Критерий'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Описание'),
        ),
    ]
