# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20170627_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='number',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер'),
        ),
    ]
